package org.gresch.quintett.domain.tonmodell;

public enum Oktavlage {
  SUBKONTRA, KONTRA, GROSZE, KLEINE, EINGESTRICHEN, ZWEIGESTRICHEN, DREIGESTRICHEN, VIERGESTRICHEN, FUENFGESTRICHEN, SECHSGESTRICHEN, SIEBENGESTRICHEN, ACHTGESTRICHEN, NEUNGESTRICHEN, ZEHNGESTRICHEN, ELFGESTRICHEN, ZWOELFGESTRICHEN, UNBEKANNT
}
